import { EmployeeType } from '../utils/types/employee-type'

export const employees: EmployeeType[] = [
    {
        identifier: "",
        firstName: 'James',
        lastName: 'Smith',
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'Robert',
        lastName: 'Jones',
        type: 'Part-time',
        discount: 5,
    },
    {
        identifier: "",
        firstName: 'Michael',
        lastName: 'Brown',
        type: 'Intern',
        discount: 5,
    },
    {
        identifier: "",
        firstName: 'David',
        lastName: 'Wilson',
        type: 'Part-time',
        discount: 5,
    },
    {
        identifier: "",
        firstName: 'William',
        lastName: 'Taylor',
        type: 'Permanent',
        discount: 10,
    },
    {
        identifier: "",
        firstName: 'Richard',
        lastName: 'Morton',
        type: 'Intern',
        discount: 5,
    },
    {
        identifier: "",
        firstName: 'Joseph',
        lastName: 'White',
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'Thomas',
        lastName: 'Martin',
        type: 'Part-time',
        discount: 8,
    },
    {
        identifier: "",
        firstName: 'Charles',
        lastName: 'Anderson',
        type: 'Permanent',
        discount: 10,
    },
    {
        identifier: "",
        firstName: 'Christopher',
        lastName: 'Anderson',
        type: 'Part-time',
        discount: 5,
    },
    {
        identifier: "",
        firstName: 'Daniel',
        lastName: 'Wang',
        type: 'Permanent',
        discount: 10,
    },
    {
        identifier: "",
        firstName: 'Matthew',
        lastName: 'Li',
        type: 'Part-time',
        discount: 8,
    },
    {
        identifier: "",
        firstName: 'Anthony',
        lastName: 'Rodriguez',
        type: 'Permanent',
        discount: 10,
    },
    {
        identifier: "",
        firstName: 'Mark',
        lastName: "O'Ryan",
        type: 'Contractor',
        discount: 0,
    },
    {
        identifier: "",
        firstName: 'Donald',
        lastName: 'Gelbero',
        type: 'Permanent',
        discount: 10,
    },
    {
        identifier: "",
        firstName: 'Steven',
        lastName: 'Tremblay',
        type: 'Part-time',
        discount: 5,
    },
    {
        identifier: "",
        firstName: 'Paul',
        lastName: 'Gagnon',
        type: 'Contractor',
        discount: 0,
    },
    {
        identifier: "",
        firstName: 'Andrew',
        lastName: 'Evans',
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'Joshua',
        lastName: 'Davies',
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'Kenneth',
        lastName: "O'Sullivan",
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'Kevin',
        lastName: 'Rodriguez',
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'Brian',
        lastName: 'Wilson',
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'George',
        lastName: 'Gomez',
        type: 'Permanent',
        discount: 15,
    },
    {
        identifier: "",
        firstName: 'John',
        lastName: 'Williams',
        type: 'Permanent',
        discount: 10,
    },
]
